### PR TITLE
test cluster summary

### PR DESCRIPTION
**Pull request by amirmalka**
waiting for:
1.  https://github.com/armosec/cadashboardbe/pull/158
2. new KS version

### CODE REVIEW

**Comment by dwertent** [comment]
@amirmalka Can we merge this?

**Comment by amirmalka** [comment]
@dwertent we could have but now I have to make some changes after the refactoring of the statuses ... I will take care of it soon

**Comment by dwertent** [comment]
@amirmalka Is there a reason not to merge this?

**Comment by kooomix** [comment]
@amirmalka @dwertent 
Is this PR relevant? If not, please close. Thanks.

**Pull request closed without merging**
